const express = require('express')
const router = express.Router()
const commentController = require('../controllers/commentController')
const { authorize, confirmUserAccess } = require('../middleware/authMiddleware')
router.post('/:mid/', authorize, commentController.createComment)
router.delete('/:mid/c/:id', authorize, confirmUserAccess, commentController.deleteComment)
router.get('/:mid/', commentController.indexComment)
router.get('/:mid/c/:id', commentController.showComment)
router.put('/:mid/c/:id', authorize, confirmUserAccess, commentController.updateComment)
module.exports = router