const express = require('express')
const router = express.Router()
const commentController = require('../controllers/commentControllerler')
const { authorize, confirmUserAccess } = require('../middleware/authMiddleware')
router.post('/:pid/', authorize, commentController.createComment)
router.delete('/:pid/c/:id', authorize, confirmUserAccess, commentController.deleteComment)
router.get('/:pid/', commentController.indexComment)
router.get('/:pid/c/:id', commentController.showComment)
router.put('/:pid/c/:id', authorize, confirmUserAccess, commentController.updateComment)
module.exports = router